pipelines:
  react:
    group: react
    materials:
      react:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/jprly/pipeline-demo.git
        branch: main
    stages:
      - install: # name of stage
          jobs:
            install: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: make
                   arguments:
                    - "install"
               - exec: # indicates type of task
                   command: make
                   arguments:
                    - "build"
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: make
                   arguments:
                    - "build"
      - test: # name of stage
          jobs:
            test: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: make
                   arguments:
                    - "test"
      - deploy: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: make
                   arguments:
                    - "deploy"
